apiVersion: v1
kind: Service
metadata:
  name: sms-frontend
  labels:
    app: sms-frontend
spec:
  selector:
    app: sms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
